[sdl]
fullscreen=true
output=texture
texture_renderer=software

[cpu]
core                 = auto
cputype              = auto
cpu_cycles           = 3000
cpu_cycles_protected = 200000
cpu_throttle         = false
cycleup              = 10
cycledown            = 20

[ipx]
ipx = true

[autoexec]
@ECHO OFF
MOUNT C /game
C:
ipxnet startserver
pause
start
